import published from "@/data/jobs.json";
import { validJob, type JobListing } from "./job-types";
import { cantonNetwork } from "./workspace";
const examples = [
  [
    "Design",
    "Brand identity for an independent studio",
    "Create a distinctive logo, a considered color palette, and a concise brand guide. Include source files and two rounds of revisions.",
    "350",
    "7 days",
    "Branding,Visual design",
  ],
  [
    "Development",
    "Build a responsive product landing page",
    "Build a fast, accessible landing page for a new product. Deliver responsive layouts, reusable components, and a clear handover.",
    "650",
    "10 days",
    "React,Frontend",
  ],
  [
    "Writing",
    "Write a clear onboarding guide",
    "Turn a product walkthrough into a friendly guide for new users. Include a quick start and common questions.",
    "180",
    "4 days",
    "Documentation,Copywriting",
  ],
  [
    "Marketing",
    "Plan a community launch campaign",
    "Develop a practical community launch plan, content calendar, and social copy for the first two weeks.",
    "420",
    "8 days",
    "Community,Strategy",
  ],
  [
    "Design",
    "Design a mobile wallet experience",
    "Design a focused wallet connection and activity experience, including empty states and errors. Deliver an interactive prototype.",
    "800",
    "14 days",
    "Product design,Mobile",
  ],
  [
    "Development",
    "Improve dashboard performance",
    "Review a React dashboard and improve loading, rendering, and mobile usability. Include a short report of the changes.",
    "500",
    "7 days",
    "React,Performance",
  ],
  [
    "Translation",
    "Localize a product into Indonesian",
    "Translate product screens and help content into natural Indonesian. Maintain a consistent glossary and tone.",
    "220",
    "5 days",
    "Indonesian,Localization",
  ],
  [
    "Operations",
    "Research and organize partner leads",
    "Build a researched list of relevant ecosystem partners using public business information. Include sources and outreach context.",
    "160",
    "5 days",
    "Research,Operations",
  ],
  [
    "Design",
    "Create a launch illustration set",
    "Design six original illustrations for a product launch. Deliver editable source files and web exports.",
    "300",
    "6 days",
    "Illustration,Launch",
  ],
  [
    "Writing",
    "Edit a technical product story",
    "Help explain a technical product through a clear, approachable narrative. Deliver a concise article and social excerpts.",
    "240",
    "4 days",
    "Editing,Storytelling",
  ],
  [
    "Development",
    "Add accessible search and filters",
    "Implement keyboard-friendly search, filters, and pagination for an existing directory. Include responsive styling.",
    "480",
    "8 days",
    "Accessibility,TypeScript",
  ],
  [
    "Marketing",
    "Produce a short product walkthrough",
    "Plan and edit a 90-second product video. Use supplied product footage and include accurate captions.",
    "320",
    "6 days",
    "Video,Product demo",
  ],
  [
    "Translation",
    "Review English interface copy",
    "Polish interface labels, help content, and error messages. Keep copy concise and consistent.",
    "150",
    "3 days",
    "English,UX writing",
  ],
  [
    "Development",
    "Create a notifications interface",
    "Build a notification inbox with useful empty states, unread indicators, and accessible controls.",
    "560",
    "9 days",
    "Next.js,Interface",
  ],
  [
    "Operations",
    "Organize a product feedback study",
    "Prepare interview prompts and synthesize feedback from supplied, consented research notes.",
    "280",
    "7 days",
    "Research,Feedback",
  ],
  [
    "Design",
    "Design a clean analytics workspace",
    "Design a responsive workspace for a small product team, with a focus on readable charts and navigation.",
    "720",
    "12 days",
    "Dashboard,UI design",
  ],
  [
    "Writing",
    "Create a concise help center",
    "Write helpful answers for the twelve most common product questions, with consistent structure and terminology.",
    "260",
    "6 days",
    "Help center,Content",
  ],
  [
    "Marketing",
    "Build a reusable social content kit",
    "Develop a set of reusable post layouts and captions for a product’s community updates.",
    "200",
    "5 days",
    "Social media,Content",
  ],
];
export function catalog(demo = false): JobListing[] {
  if (!demo)
    return (published as unknown[])
      .filter(validJob)
      .filter((j) => j.network === cantonNetwork() && !j.demo);
  return examples.map((r, i) => ({
    id: `sample-${i + 1}`,
    category: r[0],
    title: r[1],
    description: r[2],
    budget: r[3],
    asset: "USDCx",
    delivery: r[4],
    tags: r[5].split(","),
    publisher: "Example studio",
    ownerParty: "",
    ownerInstallation: "",
    network: cantonNetwork(),
    createdAt: new Date(Date.UTC(2026, 9, 6, 12, i)).toISOString(),
    demo: true,
  }));
}
